Dont implements NoCopySpan because accessibility will crash
android.text.SpannableStringBuilder.checkRange
java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0